### ISSUE TITLE
Uncaught error thrown when API goes down

### ISSUE THREAD

**Issue by beverlycodes** [dlion/node-catc#3]
If the CloudAtCost API server goes down, `CatC.execute` throws an error.  Since this is happening in a callback, this will ultimately crash the node process.

This can probably be fixed by checking for `err.code === ENETUNREACH` (and other possible failure codes) and returning something like `{ status: 'down' }`.

**Comment by beverlycodes** [comment]
Submitted a pull request to fix this.

**Comment by beverlycodes** [comment]
When you get a chance, can you do a version bump for the PR and publish to npm?  I'm running with my fork right now, but would prefer to be pulling straight from npm again.  Thanks.

**Comment by dlion** [comment]
You right, package update and pubblished, thank you!
